In [1]:
import pandas as pd

dataframe=pd.read_csv("Data/customer_shopping_behavior.csv")

In [2]:
dataframe.head()
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [3]:
dataframe.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [4]:
dataframe.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

The problem here is, can't directly substitue the overall median ; because it has differnet categories which will create bias in future.

In [ ]:
dataframe['Review Rating']=dataframe.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
dataframe.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
dataframe.columns=dataframe.columns.str.lower()

In [ ]:
dataframe.columns=dataframe.columns.str.replace(' ','_')

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount_(usd)',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'promo_code_used',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases']

In [13]:
dataframe=dataframe.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [14]:
dataframe.columns.tolist()

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'promo_code_used',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases']

Feature Engg.

In [15]:
dataframe['age_group']=pd.qcut(dataframe['age'],4,labels=['Young Adult', 'Adult', 'Middle-aged', 'Senior'])

In [20]:
dataframe[['age_group','purchase_amount']].groupby('age_group').head()

E:\Temp\ipykernel_18256\2172241553.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  dataframe[['age_group','purchase_amount']].groupby('age_group').head()

      age_group  purchase_amount
0   Middle-aged               53
1   Young Adult               64
2   Middle-aged               73
3   Young Adult               90
4   Middle-aged               49
5   Middle-aged               20
6        Senior               85
7   Young Adult               34
8   Young Adult               97
9   Middle-aged               31
11  Young Adult               68
12       Senior               72
13       Senior               51
14       Senior               53
15       Senior               81
26        Adult               20
31        Adult               79
32        Adult               67
34        Adult               91
36        Adult               69

In [23]:
dataframe['frequency_of_purchases'].count()

3900

In [ ]:
frequency_mapping={'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90}

In [25]:
dataframe['purchase_frequency_days'] = dataframe['frequency_of_purchases'].map(frequency_mapping)

In [28]:
dataframe[['frequency_of_purchases','purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [29]:
dataframe[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [ ]:
(dataframe['discount_applied']==dataframe['promo_code_used']).all()

True

There are no cases where discount is applied without using a promo code, or vice versa. (i.e;Seasonal Discount or BOGO)

In [32]:
# We can conclude that the 'discount_applied' and 'promo_code_used' columns are identical, so we can drop one of them to avoid redundancy.

dataframe=dataframe.drop(columns=['promo_code_used'])

In [34]:
dataframe.columns.tolist()

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases',
 'age_group',
 'purchase_frequency_days']

Requirements for Postgresql connection

In [38]:
%pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in e:\anaconda\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in e:\anaconda\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in e:\anaconda\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in e:\anaconda\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from sqlalchemy import create_engine

username='postgres'
password='xxxx'
host='localhost'
port='5432'
database='customer_behaviour_analysis'

engine=create_engine(f'postgresql://{username}:{password}@{host}:{port}/{database}')

table_name='customer_shopping_behavior'
dataframe.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"DataFrame successfully written to the '{table_name}' table in the '{database}' database.")

DataFrame successfully written to the 'customer_shopping_behavior' table in the 'customer_behaviour_analysis' database.

SQL

In [ ]:
%pip install pymysql

Collecting pymysqlNote: you may need to restart the kernel to use updated packages.

  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in e:\anaconda\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in e:\anaconda\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in e:\anaconda\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [ ]:
from sqlalchemy import create_engine